<div class="container-fluid" <?php if(!esMobil($uagent_obj)){ echo 'style="padding:0px 15% 0px 15%"';} ?> >
	<div class="row-fluid">
		<div class="col-md-12">
			<div class="panel panel-primary" <?php if(!esMobil($uagent_obj)){ echo 'style="margin: auto;width: 80%;padding: 00px;"';} ?> >
				<div class="panel-heading">
					<a data-toggle="collapse" href="#collapseAcerca">Acerca de <i>Arufu Creations</i></a>
				</div>
				<div id="collapseAcerca" class="panel-collapse in">
					<div class="panel-body">
						<h2><p style="text-align: center;">Acerca de</p></h2>
						<!--<p style="text-align: center;">Desplácese por el navegador.</p>-->
						
					</div>
				</div>
			</div>
			<br>
		</div>
	</div>
</div>