<?php
if(isset($_POST["boton"])){
	if($_POST["boton"] == "guardar"){
		if(isset($_POST["js"]) && ($_POST["js"] == "js")){
			$_SESSION["js"] = true;
		}
		else{
			$_SESSION["js"] = false;
		}

		if(($_POST["nav"] == "topnav") || ($_POST["nav"] == "sidenav")){
			if($_POST["nav"] == "topnav"){
				$_SESSION["nav"] = "topnav";
			}
			elseif($_POST["nav"] == "sidenav"){
				$_SESSION["nav"] = "sidenav";
			}
		}

		if(isset($_POST["mostrarWip"]) && ($_POST["mostrarWip"] == "mostrarWip")){
			$_SESSION['verWip'] = true;
		}
		else{
			$_SESSION['verWip'] = false;
		}

		if($permiteCuentas && $_SESSION["logeado"]){
			$verWip = 0;
			if($_SESSION['verWip']){$verWip = 1;}
			$sql = "UPDATE user_config, usuarios SET nav='{$_SESSION["nav"]}', verWip='{$verWip}' WHERE user_config.id_user=usuarios.id_user AND username='{$_SESSION["user"]}'";
			comandoMySql($sql);
		}
	}
	elseif("restablecer" == $_POST["boton"]){
		unset($_SESSION["js"]);
		$_SESSION["nav"] = "topnav";
		if($permiteCuentas && $_SESSION["logeado"]){
			$sql = "UPDATE user_config, usuarios SET nav='{$_SESSION["nav"]}' WHERE user_config.id_user=usuarios.id_user AND username='{$_SESSION["user"]}'";
			comandoMySql($sql);
		}
		$_SESSION['verWip'] = false;
	}
	echo '<meta http-equiv="refresh" content="1">';
}
?>

<!DOCTYPE html>
<html>
	<body style="background-color:gainsboro">
		<div class="container-fluid" <?php if(!esMobil($uagent_obj)){ echo 'style="padding:0px 15% 0px 15%"';} ?> >
			<div class="row-fluid">
				<div class="col-md-12">
					<div class="panel panel-primary" <?php if(!esMobil($uagent_obj)){ echo 'style="margin: auto;width: 80%;padding: 00px;"';} ?> >
						<div class="panel-heading">
							<a data-toggle="collapse" href="#collapseConfig">Configuración de la pagina</a>
						</div>
						<div id="collapseConfig" class="panel-collapse in">
							<div class="panel-body">
								<form action="" method="post">
									<!-- des/Activar Js -->
									<label> <input type="checkbox" id="js" name="js" value="js" <?php if(!isset($_SESSION["togglejs"]) || (isset($_SESSION["togglejs"]) && !$_SESSION["togglejs"])){echo 'disabled=""';} if(isset($_SESSION["js"]) && $_SESSION["js"]){ echo 'checked=""';} ?> /> Activar JavaScript</label>
									<?php if(!$_SESSION["togglejs"]){ echo "<br><i>No puede activar esta opción debido a que su navegador no parece soportar JavaScript.</i><br>";} ?>
									<br>

									<!-- Cambiar menu -->
									<table class="sin-bordes">
										<tr>
											<td class="sin-bordes"><label>Cambiar menu:</label></td>
											<td class="sin-bordes"><input type="radio" id="nav" name="nav" value="topnav" <?php if($_SESSION["nav"] == "topnav"){echo "checked";} if(!isset($_SESSION["js"]) || !$_SESSION["js"]){echo ' disabled=""';} ?> /> Menu superior</td>
										</tr>
										<tr>
											<td class="sin-bordes"></td>
											<td class="sin-bordes"><input type="radio" id="nav" name="nav" value="sidenav" <?php if($_SESSION["nav"] == "sidenav"){echo "checked";} if(!isset($_SESSION["js"]) || !$_SESSION["js"]){echo 'disabled=""';} ?> /> Menu lateral</td>
										</tr>
									</table>
									<?php if(!$_SESSION["togglejs"]){ echo "<i>Menu lateral requiere el uso de JS.</i><br>";} ?>

									<!-- Ver paginas en wip (solo admin) -->
									<?php
									if($_SESSION["logeado"] && ($_SESSION["admin"] > 0)){
										?>
										<label> <input type="checkbox" id="mostrarWip" name="mostrarWip" value="mostrarWip" <?php if(isset($_SESSION['verWip']) && $_SESSION['verWip']){ echo 'checked=""';} ?> /> Ver paginas WIP </label>
										<?php
									}
									?>


									<br><br>
									<button class="btn btn-primary" id="boton" name="boton" value="guardar">Guardar cambios</button>
									<button class="btn btn-danger" id="boton" name="boton" value="restablecer">Restablecer valores por defecto</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>
