<?php
$numFib = "1";
$conCero = false;
if(isset($_POST['numFib'])){
	$numFib = $_POST["numFib"];
	if(isset($_POST["conCero"])){
		$conCero = true;
	}
	///print_r(generarFibonacci($numFib, $conCero));
}
?>

<html>
	<body style="background-color:gainsboro">
		<div class="container-fluid" <?php if(!esMobil($uagent_obj)){ echo 'style="padding:0px 15% 0px 15%"';} ?> >
			<div class="row-fluid">
				<div class="col-md-12">
					<div class="panel panel-primary" <?php if(!esMobil($uagent_obj)){ echo 'style="margin: auto;width: 80%;padding: 00px;"';} ?> >
						<div class="panel-heading">
							<a data-toggle="collapse" href="#collapseFibonacci">Generador de Fibonacci</a>
						</div>
						<div id="collapseFibonacci" class="panel-collapse in">
							<div class="panel-body">
								<?php
								if(!$_SESSION["js"]){
									echo '<form action="#fiboGene" method="post">';
								}
								?>
									<label>Ingrese cuantos números de Fibonacci desea generar:</label>
									<input type="number" class="form-control" id="numFib" name="numFib" min="0" value="<?php echo $numFib; ?>" />
									<label><input type="checkbox" id="conCero" name="conCero" value="true" <?php if($conCero){echo 'checked=""';} ?>/> Empezar desde cero</label>
									<br>
									<br>
									<button <?php if($_SESSION["js"]){ echo 'onclick="generarTablaFibonacci()"';} ?> class="btn btn-primary">Generar</button>
									<br>
									<br>
									<div id="fiboGene" class="panel-collapse collapse" style="text-align:center; width: 250px;">
										<?php
										if(isset($_POST["numFib"])){
											?>
											<table>
												<th>Posicion</th>
												<th>Número</th>
												<?php
												if($numFib >= 1){
													if(!$conCero){
														$uno = 1;
													}
													else{
														$uno = 0;
													}
													echo "<tr><td>1</td><td>".$uno."</td></tr>";
												}
												if($numFib >= 2){
													$dos = 1;
													echo "<tr><td>2</td><td>".$dos."</td></tr>";
												}
												for($i = 3; $i <= $numFib; $i++){
													$tres = $uno + $dos;
													echo "<tr><td>".$i."</td><td>".$tres."</td></tr>";
													$uno = $dos;
													$dos = $tres;
													if($tres == INF){
														break;
													}
												}
												?>
											</table>
											<?php
										}
										?>
									</div>
								<?php
								if(!$_SESSION["js"]){
									echo '</form>';
								}
								?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>
