<!DOCTYPE html>
<html>
	<body style="background-color:gainsboro">
		<div class="container-fluid" <?php if(!esMobil($uagent_obj)){ echo 'style="padding:0px 15% 0px 15%"';} ?> >
			<div class="row-fluid">
				<div class="col-md-12">
					<div class="panel panel-primary" <?php if(!esMobil($uagent_obj)){ echo 'style="margin: auto;width: 80%;padding: 00px;"';} ?> >
						<div class="panel-heading">
							<a data-toggle="collapse" href="#collapseHome">Home</a>
						</div>
						<div id="collapseHome" class="panel-collapse in">
							<div class="panel-body">
								<h2><p style="text-align: center;">Bienvenido a Arufu Home Page</p></h2>
								<p style="text-align: center;">Desplácese por el navegador.</p>
								<?php
								if($permiteCuentas && !$_SESSION["logeado"]){
									?>
									<p style="text-align: center;">No es necesario tener una cuenta para usar esta pagina.</p>
									<?php
								}
								?>
							</div>
						</div>
					</div>
					<br>
				</div>
				<?php
				if($permiteCuentas && ((isset($_SESSION["logeado"]) && !$_SESSION["logeado"]) || !isset($_SESSION["logeado"]))){
					?>
					<div class="col-md-6">
						<div class="panel panel-primary" <?php if(!esMobil($uagent_obj)){ echo 'style="margin: auto;width: 90%;padding: 00px;"';} ?> >
							<div class="panel-heading">
								<a data-toggle="collapse" href="#collapseIniciar">Iniciar Sesión</a>
							</div>
							<div id="collapseIniciar" class="panel-collapse in">
								<div class="panel-body">
									<form action="?s=logear" method="post">
										<h3><p style="text-align: center;">Iniciar Sesión</p></h3>
										<label>Usuario:</label>
										<input type="text" required="" class="form-control" id="user" name="user"/>
										<label>Contraseña:</label>
										<input type="password" required="" class="form-control" id="pass" name="pass"/>
										<a href="?p=claveOlvidada&wip=true" style="color:#337ab7;">Olvide mi contraseña</a>
										<br>
										<?php
										if(isset($_SESSION["errores"]["malIngresados"]) && $_SESSION["errores"]["malIngresados"]){
											echo '<br><p style="color:red">El usuario o la contraseña no coinciden</p>';
											$_SESSION["errores"]["malIngresados"] = false;
										}
										if(isset($_SESSION["errores"]["camposLogear"]) && $_SESSION["errores"]["camposLogear"]){
											echo '<br><p style="color:red">Rellena todos los campos.</p>';
											$_SESSION["errores"]["malIngresados"] = false;
										}
										if(isset($_SESSION["errores"]["internoLogear"]) && $_SESSION["errores"]["internoLogear"]){
											echo '<br><p style="color:red">Rellena todos los campos.</p>';
											$_SESSION["errores"]["internoLogear"] = false;
										}
										?>
										<br>
										<button class="btn btn-primary">Iniciar sesión</button>
										<br>
									</form>
								</div>
							</div>
						</div>
						<br>
					</div>

					<div class="col-md-6">
						<div class="panel panel-primary" <?php if(!esMobil($uagent_obj)){ echo 'style="margin: auto;width: 90%;padding: 00px;"';} ?> >
							<div class="panel-heading">
								<a data-toggle="collapse" href="#collapseCrear">Crear Usuario</a>
							</div>
							<div id="collapseCrear" class="panel-collapse in">
								<div class="panel-body">
									<form action="?s=crearCuenta" <?php if($_SESSION["js"]){ echo 'onsubmit="return crearCuenta()"';} ?> method="post">
										<h3><p style="text-align: center;">Crear Usuario</p></h3>
										<label>Usuario:</label>
										<input type="text" required="" class="form-control" id="Cuser" name="Cuser"/>
										<p id="usuarioYaExiste" style="color:red;" <?php if(!(isset($_SESSION["errores"]["usuarioYaExiste"]) && $_SESSION["errores"]["usuarioYaExiste"])){echo 'class="panel-collapse collapse"';} $_SESSION["errores"]["usuarioYaExiste"] = false;?> >
											El usuario ya existe.</p>
										
										<label>Contraseña:</label>
										<input type="password" required="" oninput="revisarClavesOnTheFly()" class="form-control" id="Cpass" name="Cpass"/>
										<label>Repita contraseña:</label>
										<input type="password" required="" oninput="revisarClavesOnTheFly()" class="form-control" id="Cpass2" name="Cpass2"/>
										<p id="passNo" style="color:red;" <?php if(!(isset($_SESSION["errores"]["clavesCoincidencia"]) && $_SESSION["errores"]["clavesCoincidencia"])){echo 'class="panel-collapse collapse"';} $_SESSION["errores"]["clavesCoincidencia"] = false; ?> >
											Las contraseñas no coinciden.</p>
										
										<label>e-Mail:</label>
										<input type="email" required="" class="form-control" id="Cmail" name="Cmail"/>
										<p id="mailCreacion" style="color:red;" <?php if(!(isset($_SESSION["errores"]["mailCreacion"]) && $_SESSION["errores"]["mailCreacion"])){echo 'class="panel-collapse collapse"';}  $_SESSION["errores"]["mailCreacion"] = false; ?> >
											Ingrese un e-Mail valido.</p>

										<p id="camposCrear" style="color:red;" <?php if(!(isset($_SESSION["errores"]["camposCrear"]) && $_SESSION["errores"]["camposCrear"])){echo 'class="panel-collapse collapse"';} $_SESSION["errores"]["camposCrear"] = false; ?> >
											Rellene todos los campos.</p>
										<br>

										<button class="btn btn-primary">Crear cuenta</button>
										<br>
										<p id="camposCrear" style="color:red;" <?php if(!(isset($_SESSION["errores"]["usuarioCreado"]) && $_SESSION["errores"]["usuarioCreado"])){echo 'class="panel-collapse collapse"';} $_SESSION["errores"]["usuarioCreado"] = false; ?> >
											Usuario creado satisfactoriamente.</p>

										<p id="camposCrear" style="color:red;" <?php if(!(isset($_SESSION["errores"]["usuarioNoCreado"]) && $_SESSION["errores"]["usuarioNoCreado"])){echo 'class="panel-collapse collapse"';}  $_SESSION["errores"]["usuarioNoCreado"] = false; ?> >
											Ocurrio un problema creando el usuario.</p>

										<p id="camposCrear" style="color:red;" <?php if(!(isset($_SESSION["errores"]["internoCreacion"]) && $_SESSION["errores"]["internoCreacion"])){echo 'class="panel-collapse collapse"';}	 $_SESSION["errores"]["internoCreacion"] = false; ?> >
											Ha ocurrido un problema interno. Intentelo mas tarde.</p>
										
									</form>
								</div>
							</div>
						</div>
						<br>
					</div>
					<?php
				}
				?>

			</div>
		</div>
	</body>
</html>
