<div class="container-fluid" <?php if(!esMobil($uagent_obj)){ echo 'style="margin-top:3%;padding:0px 15% 0px 15%"';} ?> >
	<div class="row-fluid">
		<div class="panel w3-xlarge w3-topnav w3-blue">
			<div class="panel-heading">
				<a href="?p=home">
					<img src="resources/home-white.png" width="32" height="38" alt="Home" style="border:0;">
				</a>
				<a href="?p=verificador">Digito verificador</a>
				<a href="?p=prioridad">Calculadora de prioridad</a>
				<a href="?p=notas&wip=true">Calculadoras de notas</a>
				<a href="?p=fibonacci">Fibonacci</a>
				<a href="?p=google">Google search</a>
				<a href="?p=configuracion">Configuración</a>
			</div>
		</div>
	</div>
</div>
